#include <exception>
#include <iostream>

namespace md::test {

void testArgsParserAllSupportedForms();
void testNonBlockingQueue();
void testBookManagerCreatesSeparateBooksPerInstrument();
void testBookManagerRoutesCancelByExplicitInstrumentId();
void testBookManagerResolvesCancelByOrderIdWhenInstrumentMissing();
void testBookManagerResolvesModifyByOrderIdWhenInstrumentMissing();
void testBookManagerClearRemovesOrderMappingsForInstrument();
void testBookManagerUnknownOrderWithoutInstrumentIsUnresolved();
void testLimitOrderBookStartsEmpty();
void testLimitOrderBookReportsInstrumentId();
void testLobAddSingleBid();
void testLobAddSingleAsk();
void testLobAddAggregatesSameBidPrice();
void testLobAddAggregatesSameAskPrice();
void testLobBestBidIsHighestBidPrice();
void testLobBestAskIsLowestAskPrice();
void testLobDuplicateAddReplacesOldOrder();
void testLobCancelPartial();
void testLobCancelFullWithSize();
void testLobCancelFullWithZeroSize();
void testLobCancelLargerThanRestingSizeIsCapped();
void testLobCancelUnknownOrderIsNoop();
void testLobCancelRemovesEmptyPriceLevel();
void testLobModifySizeSamePrice();
void testLobModifyPriceLevel();
void testLobModifySideChange();
void testLobModifyUnknownOrderWithFullStateBecomesAdd();
void testLobClearEmptiesBook();
void testLobTradeIsExplicitNoop();
void testLobFillIsExplicitNoop();
void testMarketDataEventFormattingAndOrdering();
void testProcessingSummaryChronologicalViolations();
void testParserValidEvent();
void testParserNullAndDecimalPrices();
void testParserTimestampFallbackAndNumericFields();
void testParserSideAndActionCodes();
void testAsyncSnapshotWriterWritesAllJobs();
void testAsyncSnapshotWriterFinishDrainsQueue();
void testLobProcessorUpdatesBooks();
void testLobProcessorPrintsSnapshotsAtInterval();
void testLobProcessorRespectsMaxSnapshots();
void testLobProcessorFinalSummaryContainsBestBidAsk();
void testLobProcessorAsyncSnapshotsDoNotChangeFinalLobDigest();
void testSyncAndAsyncSnapshotOutputsHaveSameSnapshotCount();
void testArgsParserAcceptsLobFlag();
void testArgsParserAcceptsSnapshotOptions();
void testArgsParserRejectsSnapshotIntervalZero();
void testArgsParserAcceptsLobWithHardModes();
void testArgsParserAcceptsLobWithBenchmarkMode();
void testUsageMentionsLobOptions();
void testResultPrinterPrintsTimingForStandardMode();
void testResultPrinterPrintsThroughputForStandardMode();
void testStandardRunner();
void testStandardRunnerWithLobProcessorReconstructsExpectedBooks();
void testStandardRunnerWithLobProcessorPrintsExpectedSnapshots();
void testStandardRunnerReportsZeroChronologicalViolationsForSortedFile();
void testLobStandardFinalOutputContainsRequiredSections();
void testFlatMergeRunner();
void testHierarchicalMergeRunner();
#ifdef MD_ENABLE_ARROW
void testFeatherReaderReadsSyntheticRows();
void testFeatherReaderMapsNullPriceToUndef();
void testFeatherReaderFallsBackToTsEventWhenTsRecvColumnIsMissing();
void testFeatherFlatLobMatchesJsonFlatLobOnSynthetic();
void testFeatherHierarchyLobMatchesJsonHierarchyLobOnSynthetic();
void testFeatherFlatAndHierarchyHaveSameDigestOnSynthetic();
void testFeatherFlatAndHierarchyHaveSameDigestOnRealFolder();
#endif
void testFlatRunnerWithLobProcessorReconstructsExpectedBooks();
void testHierarchyRunnerWithLobProcessorReconstructsExpectedBooks();
void testFlatAndHierarchyLobFinalBooksAreIdentical();
void testFlatAndHierarchyLobSyntheticHaveSameMessageCount();
void testFlatAndHierarchyLobSyntheticHaveZeroChronologicalViolations();
void testFlatAndHierarchyLobSyntheticHaveSameFinalLobDigest();
void testFlatAndHierarchyLobEqualTimestampsAreDeterministic();
void testFlatLobAsyncSnapshotsMatchSyncOnSyntheticFolder();
void testBenchmarkLoggingRunsFlatAndHierarchy();
void testBenchmarkLoggingOutputsParseableReportRows();
void testBenchmarkLobRunsFlatAndHierarchy();
void testBenchmarkLobSuppressesSnapshotsByDefault();
void testBenchmarkLobOutputsEqualMessageCounts();
void testBenchmarkLobOutputsEqualFinalLobDigest();
void testBenchmarkLobLabelsShardedWorkers();
void testShardedLobTwoWorkersMatchesSequentialDigest();
void testShardedLobFourWorkersMatchesSequentialDigest();
void testShardedLobResolvesMissingInstrumentIdByOrderId();
void testShardedLobPreservesPerInstrumentOrder();
void testShardedLobUnknownOrderWithoutInstrumentGoesToUnresolvedCounter();

} // namespace md::test

int main() {
    try {
        md::test::testNonBlockingQueue();
        md::test::testBookManagerCreatesSeparateBooksPerInstrument();
        md::test::testBookManagerRoutesCancelByExplicitInstrumentId();
        md::test::testBookManagerResolvesCancelByOrderIdWhenInstrumentMissing();
        md::test::testBookManagerResolvesModifyByOrderIdWhenInstrumentMissing();
        md::test::testBookManagerClearRemovesOrderMappingsForInstrument();
        md::test::testBookManagerUnknownOrderWithoutInstrumentIsUnresolved();
        md::test::testLimitOrderBookStartsEmpty();
        md::test::testLimitOrderBookReportsInstrumentId();
        md::test::testLobAddSingleBid();
        md::test::testLobAddSingleAsk();
        md::test::testLobAddAggregatesSameBidPrice();
        md::test::testLobAddAggregatesSameAskPrice();
        md::test::testLobBestBidIsHighestBidPrice();
        md::test::testLobBestAskIsLowestAskPrice();
        md::test::testLobDuplicateAddReplacesOldOrder();
        md::test::testLobCancelPartial();
        md::test::testLobCancelFullWithSize();
        md::test::testLobCancelFullWithZeroSize();
        md::test::testLobCancelLargerThanRestingSizeIsCapped();
        md::test::testLobCancelUnknownOrderIsNoop();
        md::test::testLobCancelRemovesEmptyPriceLevel();
        md::test::testLobModifySizeSamePrice();
        md::test::testLobModifyPriceLevel();
        md::test::testLobModifySideChange();
        md::test::testLobModifyUnknownOrderWithFullStateBecomesAdd();
        md::test::testLobClearEmptiesBook();
        md::test::testLobTradeIsExplicitNoop();
        md::test::testLobFillIsExplicitNoop();
        md::test::testMarketDataEventFormattingAndOrdering();
        md::test::testProcessingSummaryChronologicalViolations();
        md::test::testParserValidEvent();
        md::test::testParserNullAndDecimalPrices();
        md::test::testParserTimestampFallbackAndNumericFields();
        md::test::testParserSideAndActionCodes();
        md::test::testAsyncSnapshotWriterWritesAllJobs();
        md::test::testAsyncSnapshotWriterFinishDrainsQueue();
        md::test::testLobProcessorUpdatesBooks();
        md::test::testLobProcessorPrintsSnapshotsAtInterval();
        md::test::testLobProcessorRespectsMaxSnapshots();
        md::test::testLobProcessorFinalSummaryContainsBestBidAsk();
        md::test::testLobProcessorAsyncSnapshotsDoNotChangeFinalLobDigest();
        md::test::testSyncAndAsyncSnapshotOutputsHaveSameSnapshotCount();
        md::test::testArgsParserAllSupportedForms();
        md::test::testArgsParserAcceptsLobFlag();
        md::test::testArgsParserAcceptsSnapshotOptions();
        md::test::testArgsParserRejectsSnapshotIntervalZero();
        md::test::testArgsParserAcceptsLobWithHardModes();
        md::test::testArgsParserAcceptsLobWithBenchmarkMode();
        md::test::testUsageMentionsLobOptions();
        md::test::testResultPrinterPrintsTimingForStandardMode();
        md::test::testResultPrinterPrintsThroughputForStandardMode();
        md::test::testStandardRunner();
        md::test::testStandardRunnerWithLobProcessorReconstructsExpectedBooks();
        md::test::testStandardRunnerWithLobProcessorPrintsExpectedSnapshots();
        md::test::testStandardRunnerReportsZeroChronologicalViolationsForSortedFile();
        md::test::testLobStandardFinalOutputContainsRequiredSections();
        md::test::testFlatMergeRunner();
        md::test::testHierarchicalMergeRunner();
#ifdef MD_ENABLE_ARROW
        md::test::testFeatherReaderReadsSyntheticRows();
        md::test::testFeatherReaderMapsNullPriceToUndef();
        md::test::testFeatherReaderFallsBackToTsEventWhenTsRecvColumnIsMissing();
        md::test::testFeatherFlatLobMatchesJsonFlatLobOnSynthetic();
        md::test::testFeatherHierarchyLobMatchesJsonHierarchyLobOnSynthetic();
        md::test::testFeatherFlatAndHierarchyHaveSameDigestOnSynthetic();
        md::test::testFeatherFlatAndHierarchyHaveSameDigestOnRealFolder();
#endif
        md::test::testFlatRunnerWithLobProcessorReconstructsExpectedBooks();
        md::test::testHierarchyRunnerWithLobProcessorReconstructsExpectedBooks();
        md::test::testFlatAndHierarchyLobFinalBooksAreIdentical();
        md::test::testFlatAndHierarchyLobSyntheticHaveSameMessageCount();
        md::test::testFlatAndHierarchyLobSyntheticHaveZeroChronologicalViolations();
        md::test::testFlatAndHierarchyLobSyntheticHaveSameFinalLobDigest();
        md::test::testFlatAndHierarchyLobEqualTimestampsAreDeterministic();
        md::test::testFlatLobAsyncSnapshotsMatchSyncOnSyntheticFolder();
        md::test::testBenchmarkLoggingRunsFlatAndHierarchy();
        md::test::testBenchmarkLoggingOutputsParseableReportRows();
        md::test::testBenchmarkLobRunsFlatAndHierarchy();
        md::test::testBenchmarkLobSuppressesSnapshotsByDefault();
        md::test::testBenchmarkLobOutputsEqualMessageCounts();
        md::test::testBenchmarkLobOutputsEqualFinalLobDigest();
        md::test::testBenchmarkLobLabelsShardedWorkers();
        md::test::testShardedLobTwoWorkersMatchesSequentialDigest();
        md::test::testShardedLobFourWorkersMatchesSequentialDigest();
        md::test::testShardedLobResolvesMissingInstrumentIdByOrderId();
        md::test::testShardedLobPreservesPerInstrumentOrder();
        md::test::testShardedLobUnknownOrderWithoutInstrumentGoesToUnresolvedCounter();
    } catch (const std::exception& e) {
        std::cerr << "TEST FAILURE: " << e.what() << '\n';
        return 1;
    }

    std::cout << "All tests passed\n";
    return 0;
}
